# Generated by Django 5.1.3 on 2024-11-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompts',
            name='prompt',
            field=models.TextField(),
        ),
    ]
