# Generated by Django 5.1.3 on 2024-11-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_alter_prompts_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompts',
            name='prompt',
            field=models.TextField(unique=True),
        ),
    ]
